In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import scipy
import os
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler, StandardScaler
from sklearn.decomposition import NMF
from imblearn.over_sampling import SMOTE 
from sklearn.ensemble import RandomForestClassifier,VotingClassifier, AdaBoostClassifier
from sklearn.model_selection import cross_val_score
from sklearn import metrics
from sklearn.decomposition import TruncatedSVD
from sklearn.neighbors import KNeighborsClassifier
from sklearn.neural_network import MLPClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import GridSearchCV, KFold
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OneHotEncoder
from sklearn.base import clone
from sklearn.metrics import precision_score,accuracy_score,f1_score,recall_score,confusion_matrix
from sklearn.neighbors import KernelDensity
from mlxtend.feature_selection import SequentialFeatureSelector
from sklearn.linear_model import LogisticRegression,Lasso
from mlxtend.feature_selection import ColumnSelector
from sklearn.pipeline import make_pipeline
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn.neural_network import MLPClassifier
from sklearn.ensemble import AdaBoostClassifier
from sklearn.ensemble import GradientBoostingClassifier,ExtraTreesClassifier
from sklearn.ensemble import ExtraTreesClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import LabelEncoder
from xgboost import XGBClassifier
from catboost import CatBoostClassifier
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report
from sklearn.feature_selection import SelectKBest
# from sklearn.feature_selection import SelectPercent
import pickle, joblib
from sklearn.preprocessing import KBinsDiscretizer, PowerTransformer, QuantileTransformer,RobustScaler

In [3]:
# In house Dataset
data_merged=pd.read_csv('merged.csv',header=None,index_col=False)

data_merged_2=data_merged.iloc[:20783]

data_merged_2=pd.DataFrame.transpose(data_merged_2)

data_merged_2.columns=data_merged_2.iloc[0].values
data_merged_2=data_merged_2.tail(-1)



data_merged_2

C:\Users\irfan\AppData\Local\Temp\ipykernel_17416\1647319165.py:2: DtypeWarning: Columns (1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,92,93,94,95,96,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,116,117,118,119,120,121,122,123,124,125,126,127,128,129,130,131,132,133,134,135) have mixed types. Specify dtype option on import or set low_memory=False.
  data_merged=pd.read_csv('merged.csv',header=None,index_col=False)


Gene SEC24B-AS1 A1BG A1CF GGACT   A2M A2ML1 A2MP1 A4GALT  \
1        2211090011-PBMC          2    2    0     5    13     0     0      0   
2        2211160007-PBMC          7    1    0     4     1     0     1      0   
3        2210050025-PBMC         14   78   68     0  2185     0     1     76   
4        2211150016-PBMC          1    3    0     3     1     0     2      0   
5        2211150008-PBMC          2    3    0     0     3     0     0      1   
..                   ...        ...  ...  ...   ...   ...   ...   ...    ...   
131      2211160008-PBMC          5    0    0     0     5     0     1      0   
132      2307270005-PBMC          5    1    0     3    13     0     2      1   
133      2307260014-PBMC          7    0    0     3    24     0     2      1   
134      2307260036-PBMC          5    1    0     4    26     0     4      1   
135  Majeed-Sabeera-PBMC          6    2    0     5    35     0     1      0   

    A4GNT  ... RNF213 SFMBT1 ERCC-00031 ERCC-00042 ERCC-00069 ERCC-00084  \
1       0  ...  826.0   46.0        0.0        0.0        0.0        0.0   
2       0  ...  678.0   32.0        0.0        0.0        0.0        0.0   
3       0  ...  403.0  101.0        0.0        0.0        0.0        0.0   
4       0  ...  861.0   37.0        0.0        0.0        0.0        0.0   
5       1  ...  378.0  244.0        0.0        0.0        0.0        0.0   
..    ...  ...    ...    ...        ...        ...        ...        ...   
131     0  ...  853.0   21.0        0.0        0.0        0.0        0.0   
132     0  ...      0      0         20          0          0          0   
133     0  ...      0      0         35          0          0          0   
134     0  ...      0      0         50          0          0          0   
135     0  ...      1      0         21          0          0          0   

    ERCC-00097 ERCC-00112 ERCC-00131 ERCC-00136  
1          0.0        0.0        0.0        0.0  
2          0.0        0.0        0.0        0.0  
3          0.0        0.0        0.0        0.0  
4          0.0        0.0        0.0        0.0  
5          0.0        0.0        0.0        0.0  
..         ...        ...        ...        ...  
131        0.0        0.0        0.0        0.0  
132         63       2555          0          6  
133         41       4374          0         10  
134         43       4827          0         14  
135         54       4963          0          4  

[135 rows x 20783 columns]

In [143]:
data_merged_2.fillna(0,inplace=True)

In [6]:
data_online=pd.read_excel('Crohns_Dataset.xlsx',header=None,index_col=False)

data_online.columns=data_online.iloc[0].values
data_online=data_online.tail(-1)
data_online

Outcomes ITGB2 ABCG2   MMP2 IFNG CXCL12 HPGDS      FN1 CYP2B6 ADH1A  ...  \
1         1    15     8  31897    0   1255     0  1027006      1     4  ...   
2         1    20   133  26183    0    111     0   467407      1     0  ...   
3         0    19    15  58028    0    895     0   573809      0     1  ...   
4         0    10    51  38045    0     20     0   236591      0     0  ...   
5         0     6    26  48239    0   1550     0   435965      0     0  ...   
6         0    17    11  24710    0    293     3  1600799      0     4  ...   
7         1     6    16  22032    0    137     0   564610      0     0  ...   
8         1    42    13  20913    0    993     0   881463      1     0  ...   
9         0    11    16  22709    0     12     0   808555      0     4  ...   
10        0     7    14  19557    0    235     0  1319261      0     2  ...   
11        1     4     4  14580    0    503     0   887571      0    11  ...   
12        1     8    21   8372    0     56     0   427432      1     0  ...   
13        0     6    24  20140    0    177     0  1125199      1     0  ...   
14        0    22    20  44296    0   1685     0   614962      0     2  ...   
15        0    17    23  32153    0   1030     0   601137      1     1  ...   
16        0    15    19  68807    0   5705     1   895780      0     4  ...   
17        1    13    42  44515    0    901     0   193947      0     1  ...   
18        0     7    23  21588    0   1441     0  1167185      0     1  ...   
19        0     5    18  56925    0   2570     0   530117      1     2  ...   
20        0     9    16  52952    0    658     0   549530      0     8  ...   
21        1    23    39  55173    0   1162     0   188531      0     0  ...   
22        1    16    33  53755    0   1608     0   379301      0     2  ...   
23        0    14    24  47742    0    957     0   432017      0     2  ...   
24        1    17     9  41991    0    284     0   538509      1     4  ...   
25        0    16    23  55573    0    127     0   250661      1    10  ...   
26        0   384   215  17995   32    431    40   400690    224   135  ...   
27        1    16    58  70283    0   2204     0   436680      0     2  ...   
28        1    18     3  25545    0   1521     0   853118      2     1  ...   
29        1     8    29  13600    0    288     0   603400      0     0  ...   
30        0     8    19  72968    0   3183     0   258134      0     5  ...   
31        1     7    13  52376    0    692     0   776626      0     1  ...   
32        1     8    37  39704    1    724     0   634939      0     1  ...   
33        0     3    29  61580    0    430     0   337977      1     0  ...   
34        1    28     9  42687    0    197     0   687440      0     1  ...   
35        0    10    10  43256    0   2190     0   474013      0     5  ...   
36        1    15    73  29090    0    457     1   386497      0     3  ...   
37        1     3    12  40697    0    869     0   454622      0     2  ...   
38        1    14    23  27450    0    283     0   779342      2     1  ...   
39        1     3    11  57238    0   1038     0   448893      0     6  ...   
40        1     8    36  34636    0   1496     0   568303      1     0  ...   

   CXCL10 HSD17B2  IL1B   IL6 SLC51A MMP9 PPARG FCGR3A NR1H4   CD44  
1       4      11     1   564     42    1  1201      4    15  15904  
2       0    1008     7   226    137    1  1069      0   181  23428  
3       1      24    20   753     75    4   837      1    64  10936  
4       1     267  2079  7136     90    0   926      0    18  12021  
5       1      95    12   298     51    1   998      0    12  16665  
6       0       4     1   140     54    1  1119      1     1  15996  
7       1       3     2    51     41    1   905      0     2  16107  
8       0       1     2   392     47    2   815      0    13   9006  
9       2       0     5   473     82    2  2026      0     6   9103  
10      2       6    46  1104     59    1  1106      0    11  1

In [11]:
X=data_online.iloc[:,1:]

Y=data_online.iloc[:,0]

In [14]:
Y=Y.astype(int)

In [18]:
(Y==1).sum()

21

In [21]:
col_1=data_merged_2.columns.values
col_2=X.columns.values

print(col_1.shape,col_2.shape)

(20783,) (28,)


In [22]:
col_similar=[]
for a in col_1:
    for b in col_2:
        if a==b:
            col_similar.append(a)
            break

In [24]:
len(col_similar)

28

In [453]:
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.25,random_state=4,stratify=Y)

In [479]:
pipe_train=Pipeline([
    # ("Minmax",MinMaxScaler()),
    # ("Yeo-johnson",PowerTransformer(method='yeo-johnson',standardize=True)),
    # ("Binss",KBinsDiscretizer(n_bins=50,encode='ordinal',strategy='quantile',dtype=np.float32,subsample='warn',random_state=55)),
    # ("NMF",NMF(n_components=15,random_state=44)),
    # ("Robust Scaler",RobustScaler()),
    ("Scaler",StandardScaler()),
    # ("Quantile",QuantileTransformer(n_quantiles=117,output_distribution='normal',random_state=77)),
    # `("SVD",TruncatedSVD(n_components=20,random_state=89))` is adding a step to the pipeline. It is applying the TruncatedSVD (Singular Value Decomposition) dimensionality reduction technique to the data.
    ("SVD",TruncatedSVD(n_components=10,random_state=890))
    # ("Robust Scaler",RobustScaler())
    # ("Yeo-johnson",PowerTransformer(method='yeo-johnson',standardize=False)),
    # ("Quantile",QuantileTransformer(n_quantiles=1000,output_distribution='normal',random_state=77))
    # ("Binss",KBinsDiscretizer(n_bins=100,encode='ordinal',strategy='quantile',dtype=np.float32,subsample='warn',random_state=55)),
    # ("NMF",NMF(n_components=10,random_state=0)),
    # ("Yeo-johnson",PowerTransformer(method='yeo-johnson',standardize=True))  
]).set_output(transform="pandas")

X_train_piped=pipe_train.fit_transform(X_train)


smote=SMOTE(k_neighbors=2,random_state=227)
X_smote,Y_smote=smote.fit_resample(X_train_piped,Y_train)

X_smote

truncatedsvd0  truncatedsvd1  truncatedsvd2  truncatedsvd3  truncatedsvd4  \
0       -1.329568       0.181943      -0.831977       0.639344       0.714855   
1       -0.865697      -0.826349       0.071736      -2.341442       0.950632   
2       -0.985623      -1.373326       1.530854      -0.399614       2.220887   
3       -0.612533      -0.645965       2.327893      -3.338289      -0.946522   
4       -0.875119      -2.588183       0.635601      -1.559754       0.342924   
5       -0.407945      -1.440853       0.353254      -1.668473      -1.037219   
6       -0.472932       0.915925       0.103519       1.891279       0.324923   
7        0.070726       0.154374       0.873843       1.232364      -0.206345   
8       -0.810917      -1.002811       0.065894       0.529135      -0.131544   
9       -1.135143      -0.607129      -0.926190       1.110040      -1.028748   
10      -1.379939       2.154876      -1.491329      -0.871799       4.133690   
11      -1.230560      -1.552771      -2.034793       2.115352      -1.993554   
12      -0.237443       0.072850      -1.575463       0.145571      -1.284021   
13      -0.198459      -0.009172      -0.846003       3.589217      -1.142762   
14       1.018764       5.359564       5.717782       0.320578      -1.351799   
15      -0.555895       0.430253      -0.449686      -0.421361      -0.407800   
16      -0.986818      -0.294168      -0.474490       0.965709      -0.350484   
17      -0.879662      -1.143923       0.225809      -0.328105       1.201137   
18      -0.726590       0.500177       0.327282       1.641120       0.671283   
19      -0.758243      -1.359876      -0.155756      -0.141780      -1.529161   
20      -0.967905       1.467825       0.873368       1.965286       1.284799   
21      -0.094693       5.501525      -4.536714      -3.446737      -1.177998   
22      -0.754261      -1.667127       0.264541      -1.334875      -0.816927   
23      -0.756114       1.210002       0.274695      -0.268303      -1.436177   
24      -0.965953      -2.075431      -0.259867       0.099582       0.760317   
25      -0.860235       0.069245       0.445606       0.167693       0.759588   
26      -0.731290       1.322748      -0.685276       1.282090       1.200522   
27      -0.810121      -0.223750      -0.177405       0.177220       0.461351   
28      19.880413      -0.649580      -0.451263       0.041164       0.392160   
29      -0.580245      -1.880892       0.804536      -1.792210      -0.578008   
30      -0.883732      -0.705919       0.539093      -0.064723       1.199356   
31      -0.872904      -0.634990       0.433693      -0.029132       1.090793   

    truncatedsvd5  truncatedsvd6  truncatedsvd7  truncatedsvd8  truncatedsvd9  
0        0.052215       0.748916      -0.345790       0.139134      -0.272764  
1        1.223115      -1.123787       1.201827      -0.205996       0.833438  
2        0.042730       0.034604       1.092365      -1.284721       0.216303  
3       -2.351234      -0.338005       1.566196       1.330114      -0.142624  
4       -0.234466       2.068431      -0.298305       0.526291       0.326944  
5        1.441350      -0.286116      -0.225686       0.151958      -0.704211  
6        0.310310      -0.054383      -0.949666       1.174744      -0.329295  
7        2.919797       0.187864       0.800153       0.121894      -1.173353  
8        0.518049       0.980708      -0.391225       0.218749       0.045190  
9       -1.072124      -0.278569      -0.313528      -0.528995      -0.576658  
10      -1.290681       0.161242       0.336020      -0.107716      -0.296763  
11      -2.178562       1.548898       0.717147       0.029336       0.058997  
12       1.056173      -0.567281       0.669614       0.454378      -0.449723  
13       0.503022      -0.157627       2.369331      -0.420733       0.665153  
14       0.083357       0.999792      -0.104462      -0.503405       0.329029  
15      -0.661617      -1.020546      -0.337387   

In [480]:
classifiers = [['Neural Network :', MLPClassifier(max_iter = 1000)],
               ['LogisticRegression :', LogisticRegression(max_iter = 1000)],
               ['ExtraTreesClassifier :', ExtraTreesClassifier()],
               ['DecisionTree :',DecisionTreeClassifier()],
               ['RandomForest :',RandomForestClassifier(n_estimators=300)], 
               ['Naive Bayes :', GaussianNB()],
               ['KNeighbours :', KNeighborsClassifier()],
               ['SVM :', SVC()],
               ['AdaBoostClassifier :', AdaBoostClassifier()],
               ['GradientBoostingClassifier: ', GradientBoostingClassifier()],
               ['XGB :', XGBClassifier()],
               ['ExtraTree',ExtraTreesClassifier(n_estimators=500)],
               ['CatBoost :', CatBoostClassifier(logging_level='Silent')]]


for name,classifier in classifiers:
    scores = cross_val_score(classifier, X_smote, Y_smote, cv=5, scoring='accuracy')
    print(name, scores.mean())

Neural Network : 0.7095238095238094
LogisticRegression : 0.6571428571428571
ExtraTreesClassifier : 0.6238095238095237
DecisionTree : 0.5380952380952381
RandomForest : 0.5619047619047619
Naive Bayes : 0.5619047619047619
KNeighbours : 0.7190476190476189
SVM : 0.6523809523809524
AdaBoostClassifier : 0.5333333333333333
GradientBoostingClassifier:  0.5619047619047619
XGB : 0.5666666666666667
ExtraTree 0.5904761904761904
CatBoost : 0.5619047619047619


In [198]:
vot=VotingClassifier([
    ('XGB',ExtraTreesClassifier(n_estimators=500)),('Cat',CatBoostClassifier(logging_level='Silent')),('GB',GradientBoostingClassifier())
],voting='soft')
scores = cross_val_score(vot, X_smote, Y_smote, cv=5, scoring='accuracy')
print(scores.mean())

0.6857142857142857


In [484]:
#MLP Optimization

mlp_gs = MLPClassifier(max_iter=20000)
parameter_space = {
    'hidden_layer_sizes': [(10,30,10),(500,)],
    'activation': ['tanh', 'relu'],
    'solver': ['sgd', 'adam'],
    'alpha': [0.05,0.01,0.1,0.5],
    'learning_rate': ['constant','adaptive'],
}

clf_mlp = GridSearchCV(mlp_gs, parameter_space, n_jobs=-1, cv=5)
clf_mlp.fit(X_smote, Y_smote)

mlp_opt=clf_mlp.best_estimator_

print(clf_mlp.best_params_)

scores = cross_val_score(mlp_opt, X_smote, Y_smote, cv=5, scoring='accuracy')

print(scores)
print(scores.mean(),scores.std())

{'activation': 'relu', 'alpha': 0.01, 'hidden_layer_sizes': (10, 30, 10), 'learning_rate': 'constant', 'solver': 'adam'}
[1.         0.71428571 0.66666667 0.83333333 0.66666667]
0.7761904761904762 0.1274198872405681


In [418]:
# Optimization
DTree=DecisionTreeClassifier()
params={'criterion':['gini', 'entropy'],
    'max_depth':[1,2,4,6,8,10,12],
    'min_samples_split':range(1,11),
    'min_samples_leaf':range(1,11)}

grid_dtree_s=GridSearchCV(DTree,params)

grid_dtree_s.fit(X_smote,Y_smote)

tree_opt_s=grid_dtree_s.best_estimator_


print(grid_dtree_s.best_params_)

{'criterion': 'gini', 'max_depth': 4, 'min_samples_leaf': 2, 'min_samples_split': 2}


In [419]:
dt=clone(tree_opt)
scores_dt = cross_val_score(dt, X_smote, Y_smote, cv=5, scoring='accuracy')

print(scores_dt)
print(scores_dt.mean(),scores_dt.std())

[0.71428571 0.42857143 0.66666667 0.5        0.66666667]
0.5952380952380951 0.11065666703449763


In [295]:
from sklearn.ensemble import BaggingClassifier
clf = BaggingClassifier(dt, n_estimators=100, random_state=0,oob_score=True)

scores = cross_val_score(clf, X_smote, Y_smote, cv=5, scoring='accuracy')

print(scores)
print(scores.mean(),scores.std())

[0.71428571 0.71428571 0.83333333 0.5        0.83333333]
0.719047619047619 0.1217782081194707


In [487]:
clone_dt=clone(mlp_opt)
clone_dt.fit(X_smote,Y_smote)

y_predict=clone_dt.predict(X_test_piped)
acc=accuracy_score(Y_test,y_predict)
pr=precision_score(Y_test,y_predict)
recall=recall_score(Y_test,y_predict)
f1=f1_score(Y_test,y_predict)
print(acc,pr,recall,f1)

0.4 0.42857142857142855 0.6 0.5


In [248]:
#optimizaing random forest
grid_space={'max_depth':[10,50,100,None],
              'n_estimators':[200,300,700],
              'max_features':[7,9,13],
              'min_samples_leaf':[1,2,3],
              'min_samples_split':[1,2,3]
           }
grid_RF = GridSearchCV(RandomForestClassifier(), grid_space, refit = True) 

# fitting the model for grid search 
grid_RF.fit(X_train_piped, Y_train) 

print(grid_RF.best_params_)
rfff=grid_RF.best_estimator_

{'max_depth': 10, 'max_features': 9, 'min_samples_leaf': 3, 'min_samples_split': 3, 'n_estimators': 300}


In [249]:
rf=clone(rfff)
scores_rf = cross_val_score(rf, X_train_piped, Y_train, cv=5, scoring='accuracy')

print(scores_rf)
print(scores_rf.mean(),scores_rf.std())

[0.66666667 0.5        0.66666667 0.66666667 0.33333333]
0.5666666666666667 0.13333333333333333


In [421]:
# XGBOOST
from xgboost import XGBClassifier

xgb=XGBClassifier()

parameters = {
    'max_depth': range (2, 20, 1),
    'n_estimators': range(60, 500, 40),
    'learning_rate': [0.1, 0.01, 0.05]
}
xgb_grid=GridSearchCV(xgb,param_grid=parameters,cv=5,n_jobs=-1)

xgb_grid.fit(X_smote,Y_smote)

xgb_best=xgb_grid.best_estimator_

print(xgb_grid.best_params_)

{'learning_rate': 0.01, 'max_depth': 2, 'n_estimators': 100}


In [477]:

scores = cross_val_score(xgb_best,X_smote,Y_smote, cv=5, scoring='accuracy')
print(scores.mean())

0.5380952380952382


In [423]:
CAT=CatBoostClassifier()
parameters = {'depth'         : [4,5,6,7,8,9, 10],
                 'learning_rate' : [0.01,0.02,0.03,0.04],
                  'iterations'    : [10, 20,30,40,50,60,70,80,90, 100],
                  'logging_level':['Silent']
                 }
CAT_grid=GridSearchCV(CAT,param_grid=parameters,cv=5,n_jobs=-1)

CAT_grid.fit(X_smote,Y_smote)

CAT_best=CAT_grid.best_estimator_

print(CAT_grid.best_params_)

{'depth': 4, 'iterations': 10, 'learning_rate': 0.02, 'logging_level': 'Silent'}


In [478]:
scores = cross_val_score(CAT_best, X_smote,Y_smote, cv=5, scoring='accuracy')
print(scores.mean())

0.557142857142857


In [486]:
X_test_piped=pipe_train.transform(X_test)

In [426]:
clone_CAT=clone(CAT_best)
clone_CAT.fit(X_smote,Y_smote)

y_predict=clone_CAT.predict(X_test_piped)
acc=accuracy_score(Y_test,y_predict)
pr=precision_score(Y_test,y_predict)
recall=recall_score(Y_test,y_predict)
f1=f1_score(Y_test,y_predict)
print(acc,pr,recall,f1)

0.6 1.0 0.2 0.33333333333333337


In [413]:
clone_CAT=clone(xgb_best)
clone_CAT.fit(X_smote,Y_smote)

y_predict=clone_CAT.predict(X_test_piped)
acc=accuracy_score(Y_test,y_predict)
pr=precision_score(Y_test,y_predict)
recall=recall_score(Y_test,y_predict)
f1=f1_score(Y_test,y_predict)
print(acc,pr,recall,f1)

0.6 0.6666666666666666 0.4 0.5


In [258]:
exT=ExtraTreesClassifier()
parameters = {
    'max_depth': range (2, 20, 1),
    'n_estimators': range(60, 500, 40),
}
exT_grid=GridSearchCV(exT,param_grid=parameters,cv=5,n_jobs=-1)

exT_grid.fit(X_smote,Y_smote)

exT_best=exT_grid.best_estimator_

print(exT_grid.best_params_)

{'max_depth': 17, 'n_estimators': 380}


In [326]:
GB=GradientBoostingClassifier()
scores = cross_val_score(GB, X_smote,Y_smote, cv=5, scoring='accuracy')
print(scores.mean())

0.7904761904761906


In [324]:
abc = AdaBoostClassifier(base_estimator=DecisionTreeClassifier(random_state = 11, max_features = "auto", class_weight = "auto",max_depth = None))

parameters = {'base_estimator__max_depth':[i for i in range(2,11,2)],
              'base_estimator__min_samples_leaf':[5,10],
              'n_estimators':[10,50,250,1000],
              'learning_rate':[0.01,0.1]}

clf = GridSearchCV(abc, parameters,verbose=3,scoring='accuracy',n_jobs=-1)
clf.fit(X_train_piped,Y_train)

abc_best=clf.best_estimator_

print(clf.best_params_)

scores = cross_val_score(abc_best, X_smote,Y_smote, cv=5, scoring='accuracy')
print(scores.mean())

Fitting 5 folds for each of 80 candidates, totalling 400 fits


ValueError: 
All the 400 fits failed.
It is very likely that your model is misconfigured.
You can try to debug the error by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
400 fits failed with the following error:
Traceback (most recent call last):
  File "c:\Users\irfan\anaconda3_new\lib\site-packages\sklearn\model_selection\_validation.py", line 686, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "c:\Users\irfan\anaconda3_new\lib\site-packages\sklearn\ensemble\_weight_boosting.py", line 162, in fit
    sample_weight, estimator_weight, estimator_error = self._boost(
  File "c:\Users\irfan\anaconda3_new\lib\site-packages\sklearn\ensemble\_weight_boosting.py", line 569, in _boost
    return self._boost_real(iboost, X, y, sample_weight, random_state)
  File "c:\Users\irfan\anaconda3_new\lib\site-packages\sklearn\ensemble\_weight_boosting.py", line 578, in _boost_real
    estimator.fit(X, y, sample_weight=sample_weight)
  File "c:\Users\irfan\anaconda3_new\lib\site-packages\sklearn\tree\_classes.py", line 889, in fit
    super().fit(
  File "c:\Users\irfan\anaconda3_new\lib\site-packages\sklearn\tree\_classes.py", line 177, in fit
    self._validate_params()
  File "c:\Users\irfan\anaconda3_new\lib\site-packages\sklearn\base.py", line 581, in _validate_params
    validate_parameter_constraints(
  File "c:\Users\irfan\anaconda3_new\lib\site-packages\sklearn\utils\_param_validation.py", line 97, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'class_weight' parameter of DecisionTreeClassifier must be an instance of 'dict', an instance of 'list', a str among {'balanced'} or None. Got 'auto' instead.


In [264]:
voting_Boosts=VotingClassifier(estimators=[
    ('xgb',xgb_best),
    ('extraTree',abc_best),
    ('CAT',CAT_best)
],voting='soft')

scores = cross_val_score(voting_Boosts, X_train_piped,Y_train, cv=5, scoring='accuracy')
print(scores.mean())

c:\Users\irfan\anaconda3_new\lib\site-packages\sklearn\ensemble\_base.py:166: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
c:\Users\irfan\anaconda3_new\lib\site-packages\sklearn\ensemble\_base.py:166: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
c:\Users\irfan\anaconda3_new\lib\site-packages\sklearn\ensemble\_base.py:166: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
c:\Users\irfan\anaconda3_new\lib\site-packages\sklearn\ensemble\_base.py:166: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
c:\Users\irfan\anaconda3_new\lib\site-packages\sklearn\ensemble\_base.py:166: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(


0.7333333333333334


In [461]:
from mlxtend.feature_selection import ColumnSelector
col_similar_2=pd.DataFrame(col_similar)

from sklearn.pipeline import make_pipeline


pipe = make_pipeline(
                     ColumnSelector(cols=col_similar),
                     pipe_train,
                     mlp_opt)

pipe.fit(X_train, Y_train)

Pipeline(steps=[('columnselector',
                 ColumnSelector(cols=['ABCB1', 'ABCG2', 'ACOX1', 'ADH1A',
                                      'ADH1C', 'CCL2', 'CD44', 'CD86', 'CXCL10',
                                      'CXCL12', 'CYP2B6', 'CYP2S1', 'FCGR3A',
                                      'FN1', 'HPGDS', 'HSD17B2', 'ICAM1',
                                      'IFNG', 'IL1B', 'IL6', 'ITGB2', 'MMP2',
                                      'MMP9', 'NR1H4', 'SLC51A', 'PPARG',
                                      'PTPRC', 'UGT1A3'])),
                ('pipeline',
                 Pipeline(steps=[('Scaler', StandardScaler()),
                                 ('SVD',
                                  TruncatedSVD(n_components=15,
                                               random_state=890))])),
                ('mlpclassifier',
                 MLPClassifier(alpha=0.01, hidden_layer_sizes=(10, 30, 10),
                               learning_rate='adaptive', max_iter=800))])

In [465]:
import pickle
with open('Crohns_MLP_ver1.pkl','wb') as file:
    pickle.dump(pipe,file)

In [462]:
pipe.predict(X_test)

array([1, 1, 0, 0, 1, 0, 0, 1, 1, 1])

In [463]:
Y_test

4     0
15    0
27    1
1     1
8     1
10    0
25    0
24    1
17    1
14    0
Name: Outcomes, dtype: int32

In [464]:
pipe.predict(data_merged_2)

array([0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0])

In [345]:
# Hyperparameter tuning using GridSearchCV
param_grid = {'C': [0.001, 0.01, 0.1, 1, 10, 100], 'max_iter': [100, 500, 1000]}
grid_search = GridSearchCV(LogisticRegression(solver='liblinear'), param_grid, cv=5)
grid_search.fit(X_smote, Y_smote)

# Best hyperparameters
best_params = grid_search.best_params_

# Use the best estimator from the grid search
best_logreg = grid_search.best_estimator_

# Evaluate the model
y_pred = best_logreg.predict(X_test_piped)
accuracy = accuracy_score(Y_test, y_pred)

print(f"Best Hyperparameters: {best_params}")
print(f"Logistic Regression Accuracy: {accuracy}")
print(confusion_matrix(Y_test, y_pred))
print(classification_report(Y_test, y_pred))

Best Hyperparameters: {'C': 0.1, 'max_iter': 100}
Logistic Regression Accuracy: 0.7
[[4 1]
 [2 3]]
              precision    recall  f1-score   support

           0       0.67      0.80      0.73         5
           1       0.75      0.60      0.67         5

    accuracy                           0.70        10
   macro avg       0.71      0.70      0.70        10
weighted avg       0.71      0.70      0.70        10



In [505]:
loaded_model = joblib.load('Crohns_CAT_ver1.pkl')

In [500]:
y_predict=loaded_model.predict_proba(X_test)

In [498]:
accuracy_score(Y_test,y_predict)

0.7

In [506]:
loaded_model.predict_proba(data_merged_2)

array([[0.50035619, 0.49964381],
       [0.50217196, 0.49782804],
       [0.48109691, 0.51890309],
       [0.48367279, 0.51632721],
       [0.49973863, 0.50026137],
       [0.50255355, 0.49744645],
       [0.48366485, 0.51633515],
       [0.50280292, 0.49719708],
       [0.48334529, 0.51665471],
       [0.48399237, 0.51600763],
       [0.50192652, 0.49807348],
       [0.50243068, 0.49756932],
       [0.48419124, 0.51580876],
       [0.48314644, 0.51685356],
       [0.49944465, 0.50055535],
       [0.48399318, 0.51600682],
       [0.48328611, 0.51671389],
       [0.48332978, 0.51667022],
       [0.48487808, 0.51512192],
       [0.48399318, 0.51600682],
       [0.48334584, 0.51665416],
       [0.48328896, 0.51671104],
       [0.48103835, 0.51896165],
       [0.48499026, 0.51500974],
       [0.50192652, 0.49807348],
       [0.48149748, 0.51850252],
       [0.50217196, 0.49782804],
       [0.50217196, 0.49782804],
       [0.50192652, 0.49807348],
       [0.50192652, 0.49807348],
       [0.